title: SysFlow field mapping
order: 1
backends:
  - sf-processor

logsources:
    sysflow:
      product: linux
      service: sysflow
      conditions:
         event.provider: sysflow
   
fieldmappings:
    Image: sf.proc.exe
    CommandLine: sf.proc.cmdline
    ParentImage: sf.pproc.exe
    ParentCommandLine: sf.pproc.cmdline
    